import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { UserRoleProvider } from "@/context/UserRoleContext";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-poppins",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Visnext",
  description: "Generated by Visnext Employee",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        <div className="flex flex-1 min-h-screen w-full">
          <div className="relative w-[40%] hidden md:block">
            <Image
              alt="Manage Bug Image"
              src="/images/HomeImage.png"
              fill
              priority
              className="object-cover"
            />
          </div>
          <div className="flex flex-1 bg-white flex-col">
            <UserRoleProvider>{children}</UserRoleProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
